version: '3'
services:
  backend:
    build: ./backend
    environment:
      - FLASK_DEBUG=true
      - PYTHONPATH=/app
    ports:
      - "5001:5001"
    volumes:
      - ./backend:/app
      - sqlite_data:/app/database
    command: ["sh", "/app/entrypoint.sh"]

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:5001/api
    stdin_open: true

volumes:
  sqlite_data:
